<?php

namespace Database\Seeders;

use App\Models\Patient;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        // MRNs use a fixed historical date prefix so they are stable across re-seeds
        $mrnDate = '20260509';

        $patients = [
            [
                'mrn'        => "MRN-{$mrnDate}-0001",
                'first_name' => 'Kato',
                'last_name'  => 'Wasswa',
                'dob'        => '1990-03-15',
                'gender'     => 'male',
                'blood_group'=> 'O+',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-001',
                'email'      => 'kato.wasswa@example.com',
                'national_id'=> 'CM90031500001',
                'address'    => 'Kampala, Nakawa Division',
                'emergency_contact_name'  => 'Nalwoga Wasswa',
                'emergency_contact_phone' => '+256-700-200-001',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0002",
                'first_name' => 'Aisha',
                'last_name'  => 'Nabirye',
                'dob'        => '1985-07-22',
                'gender'     => 'female',
                'blood_group'=> 'A+',
                'marital_status' => 'single',
                'phone'      => '+256-700-100-002',
                'email'      => 'aisha.nabirye@example.com',
                'national_id'=> 'CF85072200002',
                'address'    => 'Kampala, Makindye Division',
                'emergency_contact_name'  => 'Ibrahim Nabirye',
                'emergency_contact_phone' => '+256-700-200-002',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0003",
                'first_name' => 'Robert',
                'last_name'  => 'Mukasa',
                'dob'        => '1978-11-08',
                'gender'     => 'male',
                'blood_group'=> 'B+',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-003',
                'email'      => 'robert.mukasa@example.com',
                'national_id'=> 'CM78110800003',
                'address'    => 'Entebbe, Wakiso District',
                'emergency_contact_name'  => 'Florence Mukasa',
                'emergency_contact_phone' => '+256-700-200-003',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0004",
                'first_name' => 'Fatuma',
                'last_name'  => 'Nantongo',
                'dob'        => '1995-02-14',
                'gender'     => 'female',
                'blood_group'=> 'AB+',
                'marital_status' => 'single',
                'phone'      => '+256-700-100-004',
                'email'      => 'fatuma.nantongo@example.com',
                'national_id'=> 'CF95021400004',
                'address'    => 'Kampala, Kawempe Division',
                'emergency_contact_name'  => 'Hassan Nantongo',
                'emergency_contact_phone' => '+256-700-200-004',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0005",
                'first_name' => 'David',
                'last_name'  => 'Opolot',
                'dob'        => '2001-06-30',
                'gender'     => 'male',
                'blood_group'=> 'O-',
                'marital_status' => 'single',
                'phone'      => '+256-700-100-005',
                'email'      => 'david.opolot@example.com',
                'national_id'=> 'CM01063000005',
                'address'    => 'Mbale, Mbale District',
                'emergency_contact_name'  => 'Moses Opolot',
                'emergency_contact_phone' => '+256-700-200-005',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0006",
                'first_name' => 'Prossy',
                'last_name'  => 'Namukasa',
                'dob'        => '1970-09-05',
                'gender'     => 'female',
                'blood_group'=> 'A-',
                'marital_status' => 'widowed',
                'phone'      => '+256-700-100-006',
                'email'      => 'prossy.namukasa@example.com',
                'national_id'=> 'CF70090500006',
                'address'    => 'Jinja, Jinja District',
                'emergency_contact_name'  => 'Sarah Namukasa',
                'emergency_contact_phone' => '+256-700-200-006',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0007",
                'first_name' => 'Emmanuel',
                'last_name'  => 'Byaruhanga',
                'dob'        => '1988-04-18',
                'gender'     => 'male',
                'blood_group'=> 'B-',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-007',
                'email'      => 'emmanuel.byaruhanga@example.com',
                'national_id'=> 'CM88041800007',
                'address'    => 'Mbarara, Mbarara District',
                'emergency_contact_name'  => 'Ruth Byaruhanga',
                'emergency_contact_phone' => '+256-700-200-007',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0008",
                'first_name' => 'Harriet',
                'last_name'  => 'Akello',
                'dob'        => '1993-12-25',
                'gender'     => 'female',
                'blood_group'=> 'O+',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-008',
                'email'      => 'harriet.akello@example.com',
                'national_id'=> 'CF93122500008',
                'address'    => 'Gulu, Gulu District',
                'emergency_contact_name'  => 'Peter Akello',
                'emergency_contact_phone' => '+256-700-200-008',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0009",
                'first_name' => 'Ivan',
                'last_name'  => 'Tumwebaze',
                'dob'        => '1983-08-03',
                'gender'     => 'male',
                'blood_group'=> 'AB-',
                'marital_status' => 'divorced',
                'phone'      => '+256-700-100-009',
                'email'      => 'ivan.tumwebaze@example.com',
                'national_id'=> 'CM83080300009',
                'address'    => 'Kampala, Central Division',
                'emergency_contact_name'  => 'Agnes Tumwebaze',
                'emergency_contact_phone' => '+256-700-200-009',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0010",
                'first_name' => 'Zainab',
                'last_name'  => 'Nakawunde',
                'dob'        => '1998-05-20',
                'gender'     => 'female',
                'blood_group'=> 'A+',
                'marital_status' => 'single',
                'phone'      => '+256-700-100-010',
                'email'      => 'zainab.nakawunde@example.com',
                'national_id'=> 'CF98052000010',
                'address'    => 'Masaka, Masaka District',
                'emergency_contact_name'  => 'Yusuf Nakawunde',
                'emergency_contact_phone' => '+256-700-200-010',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0011",
                'first_name' => 'Patrick',
                'last_name'  => 'Okello',
                'dob'        => '1975-01-11',
                'gender'     => 'male',
                'blood_group'=> 'B+',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-011',
                'email'      => 'patrick.okello@example.com',
                'national_id'=> 'CM75011100011',
                'address'    => 'Lira, Lira District',
                'emergency_contact_name'  => 'Mary Okello',
                'emergency_contact_phone' => '+256-700-200-011',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0012",
                'first_name' => 'Lydia',
                'last_name'  => 'Nanyonga',
                'dob'        => '2003-10-07',
                'gender'     => 'female',
                'blood_group'=> 'O+',
                'marital_status' => 'single',
                'phone'      => '+256-700-100-012',
                'email'      => 'lydia.nanyonga@example.com',
                'national_id'=> 'CF03100700012',
                'address'    => 'Kampala, Rubaga Division',
                'emergency_contact_name'  => 'John Nanyonga',
                'emergency_contact_phone' => '+256-700-200-012',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0013",
                'first_name' => 'Samuel',
                'last_name'  => 'Kibuuka',
                'dob'        => '1965-03-28',
                'gender'     => 'male',
                'blood_group'=> 'A+',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-013',
                'email'      => 'samuel.kibuuka@example.com',
                'national_id'=> 'CM65032800013',
                'address'    => 'Fort Portal, Kabarole District',
                'emergency_contact_name'  => 'Grace Kibuuka',
                'emergency_contact_phone' => '+256-700-200-013',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0014",
                'first_name' => 'Rebecca',
                'last_name'  => 'Zawedde',
                'dob'        => '1992-07-16',
                'gender'     => 'female',
                'blood_group'=> 'AB+',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-014',
                'email'      => 'rebecca.zawedde@example.com',
                'national_id'=> 'CF92071600014',
                'address'    => 'Kampala, Nakawa Division',
                'emergency_contact_name'  => 'James Zawedde',
                'emergency_contact_phone' => '+256-700-200-014',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0015",
                'first_name' => 'Godfrey',
                'last_name'  => 'Ssali',
                'dob'        => '1980-11-02',
                'gender'     => 'male',
                'blood_group'=> 'O-',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-015',
                'email'      => 'godfrey.ssali@example.com',
                'national_id'=> 'CM80110200015',
                'address'    => 'Soroti, Soroti District',
                'emergency_contact_name'  => 'Betty Ssali',
                'emergency_contact_phone' => '+256-700-200-015',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0016",
                'first_name' => 'Juliet',
                'last_name'  => 'Namusoke',
                'dob'        => '1997-04-09',
                'gender'     => 'female',
                'blood_group'=> 'B+',
                'marital_status' => 'single',
                'phone'      => '+256-700-100-016',
                'email'      => 'juliet.namusoke@example.com',
                'national_id'=> 'CF97040900016',
                'address'    => 'Wakiso, Wakiso District',
                'emergency_contact_name'  => 'Paul Namusoke',
                'emergency_contact_phone' => '+256-700-200-016',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0017",
                'first_name' => 'Charles',
                'last_name'  => 'Mugisha',
                'dob'        => '1972-09-14',
                'gender'     => 'male',
                'blood_group'=> 'A-',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-017',
                'email'      => 'charles.mugisha@example.com',
                'national_id'=> 'CM72091400017',
                'address'    => 'Kabale, Kabale District',
                'emergency_contact_name'  => 'Christine Mugisha',
                'emergency_contact_phone' => '+256-700-200-017',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0018",
                'first_name' => 'Mariam',
                'last_name'  => 'Kyazze',
                'dob'        => '2000-01-27',
                'gender'     => 'female',
                'blood_group'=> 'O+',
                'marital_status' => 'single',
                'phone'      => '+256-700-100-018',
                'email'      => 'mariam.kyazze@example.com',
                'national_id'=> 'CF00012700018',
                'address'    => 'Kampala, Makindye Division',
                'emergency_contact_name'  => 'Ali Kyazze',
                'emergency_contact_phone' => '+256-700-200-018',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0019",
                'first_name' => 'Stephen',
                'last_name'  => 'Kigozi',
                'dob'        => '1960-06-19',
                'gender'     => 'male',
                'blood_group'=> 'B-',
                'marital_status' => 'married',
                'phone'      => '+256-700-100-019',
                'email'      => 'stephen.kigozi@example.com',
                'national_id'=> 'CM60061900019',
                'address'    => 'Hoima, Hoima District',
                'emergency_contact_name'  => 'Esther Kigozi',
                'emergency_contact_phone' => '+256-700-200-019',
            ],
            [
                'mrn'        => "MRN-{$mrnDate}-0020",
                'first_name' => 'Agnes',
                'last_name'  => 'Nakabugo',
                'dob'        => '1987-08-31',
                'gender'     => 'female',
                'blood_group'=> 'AB-',
                'marital_status' => 'divorced',
                'phone'      => '+256-700-100-020',
                'email'      => 'agnes.nakabugo@example.com',
                'national_id'=> 'CF87083100020',
                'address'    => 'Kampala, Central Division',
                'emergency_contact_name'  => 'Joseph Nakabugo',
                'emergency_contact_phone' => '+256-700-200-020',
            ],
        ];

        foreach ($patients as $data) {
            // Create the user account for the patient
            $user = User::firstOrCreate(
                ['email' => $data['email']],
                [
                    'name'     => $data['first_name'] . ' ' . $data['last_name'],
                    'password' => Hash::make('Patient@123'),
                    'role'     => 'patient',
                    'status'   => 'active',
                ]
            );

            Patient::firstOrCreate(
                ['mrn' => $data['mrn']],
                [
                    'user_id'                 => $user->id,
                    'first_name'              => $data['first_name'],
                    'last_name'               => $data['last_name'],
                    'date_of_birth'           => $data['dob'],
                    'gender'                  => $data['gender'],
                    'blood_group'             => $data['blood_group'],
                    'marital_status'          => $data['marital_status'],
                    'phone_number'            => $data['phone'],
                    'email'                   => $data['email'],
                    'national_id'             => $data['national_id'],
                    'address'                 => $data['address'],
                    'emergency_contact_name'  => $data['emergency_contact_name'],
                    'emergency_contact_phone' => $data['emergency_contact_phone'],
                ]
            );
        }
    }
}
